// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        BaseEcharts: typeof import('./src/components/BaseEcharts.vue')['default'];
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}

export {};
